I-Tul Framework: Paginate Class Reference
Paginate Class Reference
Public Member Functions
show_page_links ($options_array)
Return string containing the paging links.
build_pagination ()
Calculate which links to show, and save to an array to be accessed later.
print_page_info ()
Return a string of HTML containing how many pages there are, and the current page.
first_page_link ()
Return an HTML string containing a link to the first page if the first page link is not currently being shown.
last_page_link ()
Return an HTML string containing a link to the last page if the last page link is not currently being shown.
print_numbers ()
Return an HTML string containing a page links.
Data Fields
$options
$buffer
$page_array
Detailed Description
Definition at line 3 of file Paginate.php.
Member Function Documentation
build_pagination ()
Returns
array
Definition at line 71 of file Paginate.php.
Referenced by show_page_links().
first_page_link ()
Returns
string
Definition at line 132 of file Paginate.php.
Referenced by show_page_links().
last_page_link ()
Returns
string
Definition at line 149 of file Paginate.php.
Referenced by show_page_links().
print_numbers ()
Returns
string
Definition at line 166 of file Paginate.php.
Referenced by show_page_links().
print_page_info ()
Returns
string
Definition at line 118 of file Paginate.php.
Referenced by show_page_links().
show_page_links ($options_array)
Pass in an array of options, overwriting defaults.
Parameters
array $options_array
Returns
string
Definition at line 28 of file Paginate.php.
References $buffer, build_pagination(), first_page_link(), last_page_link(), print_numbers(), and print_page_info().
Referenced by Scaffold\paging_links().
Field Documentation
$buffer
Definition at line 17 of file Paginate.php.
Referenced by show_page_links().
$options
Initial value:
= array(
                        'current_page'          => '0',
                        'total_results'         => '0',
                        'results_per_page'      => '0',
                        'maximum_links'         => '10',
                        'url_format'            => '?page=[x]',
                        'wrapper_class'         => 'pagination',
                        'first_page_link'       => '&laquo; First',
                        'last_page_link'        => 'Last &raquo;',
                        'page_info_box'         => 'PAGE [x] OF [y]',
                )
Definition at line 6 of file Paginate.php.
$page_array
Definition at line 18 of file Paginate.php.
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/helper/Paginate.php