I-Tul Framework: Db Class Reference
Db Class Reference
Public Member Functions
__construct ()
query ($query)
Execute a query.
get_row ($query)
Fetch a single row from the database.
get_rows ($query)
Fetch multiple rows from the database.
column_names ($table_name)
Get the column names for a table.
column_exists ($table_name, $column_name)
Check if a column exists in a table.
table_info ($table_name, $force_table_info_update=FALSE)
Get an array of table info.
get_primary_key ($table_name)
Get the primary key column name for a table.
insert ($table, $data)
Insert a record with a keyed array of values.
update ($table, $data, $where)
Update a record with a keyed array of values.
escape ($value)
Escape a string.
stripslashes_deep ($value)
Recursively remove slash characters from an array or string.
get_table_names ()
Get all of the table names for the current database, store the resulting array in $this->tables.
get_enum ($table, $field, $ucfirst_values=TRUE)
Get valid enum values for a column.
begin ()
Begin transaction.
commit ()
Commit transaction.
rollback ()
Roll back transaction.
get_column_names ($table_name)
get_table_info ($table_name)
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Static Public Member Functions
static & Instance ()
Db class is a singleton.
Data Fields
$conn
$q
$num_rows
$query_count = 0
Protected Attributes
$table_info = array()
$error
Static Protected Attributes
static $_instance = NULL
Detailed Description
Definition at line 3 of file Db.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 33 of file Db.php.
Member Function Documentation
begin ()
Returns
Db
Definition at line 499 of file Db.php.
References query().
column_exists ($table_name, $column_name)
Parameters
string $table_name
string $column_name
Returns
bool
Definition at line 163 of file Db.php.
References column_names().
Referenced by Scaffold\set_join_table().
column_names ($table_name)
Parameters
string $table_name
Returns
mixed
Definition at line 140 of file Db.php.
References table_info().
Referenced by column_exists(), and get_column_names().
commit ()
Returns
Db
Definition at line 511 of file Db.php.
References query().
escape ($value)
Parameters
mixed $value
Returns
mixed
Definition at line 389 of file Db.php.
Referenced by insert(), and update().
get_column_names ($table_name)
Definition at line 531 of file Db.php.
References column_names().
get_enum ($table, $field, $ucfirst_values = TRUE)
(borrowed from php.net)
Parameters
string $table
string $field
bool $ucfirst_values
Returns
<type>
Definition at line 464 of file Db.php.
References query().
get_primary_key ($table_name)
Parameters
string $table_name
Returns
mixed
Definition at line 227 of file Db.php.
References get_table_info(), and table_info().
Referenced by Scaffold\search().
get_row ($query)
Returns array on success, FALSE on no result.
Parameters
string $query
Returns
array|bool
Definition at line 90 of file Db.php.
References query(), and stripslashes_deep().
Referenced by Scaffold\search().
get_rows ($query)
Returns array on success, FALSE on no result.
Parameters
string $query
Returns
array|bool
Definition at line 113 of file Db.php.
References query(), and stripslashes_deep().
Referenced by Model_Base\get(), Scaffold\search(), and table_info().
get_table_info ($table_name)
Definition at line 532 of file Db.php.
References table_info().
Referenced by get_primary_key(), and Scaffold\set_table_name().
get_table_names ()
Returns
bool
Definition at line 435 of file Db.php.
References query().
insert ($table, $data)
Returns the integer
Parameters
string $table
array $data
Returns
mixed.
Definition at line 257 of file Db.php.
References $table_info, escape(), query(), stripslashes_deep(), and table_info().
static& Instance () static
Returns
object
Definition at line 19 of file Db.php.
Referenced by Framework\load_helper().
query ($query)
Parameters
string $query
Returns
bool
Definition at line 64 of file Db.php.
Referenced by begin(), commit(), get_enum(), get_row(), get_rows(), get_table_names(), insert(), rollback(), and update().
rollback ()
Returns
Db
Definition at line 523 of file Db.php.
References query().
stripslashes_deep ($value)
Parameters
mixed $value
Returns
mixed
Definition at line 410 of file Db.php.
Referenced by get_row(), get_rows(), insert(), and update().
table_info ($table_name, $force_table_info_update = FALSE)
Parameters
string $table_name
Returns
array
Definition at line 188 of file Db.php.
References get_rows().
Referenced by column_names(), get_primary_key(), get_table_info(), insert(), and update().
update ($table, $data, $where)
Parameters
string $table
array $data
string $where
Returns
bool
Definition at line 322 of file Db.php.
References $table_info, escape(), query(), stripslashes_deep(), and table_info().
Field Documentation
$_instance = NULL static protected
Definition at line 9 of file Db.php.
$conn
Definition at line 5 of file Db.php.
$error protected
Definition at line 11 of file Db.php.
$num_rows
Definition at line 7 of file Db.php.
$q
Definition at line 6 of file Db.php.
$query_count = 0
Definition at line 8 of file Db.php.
$table_info = array() protected
Definition at line 10 of file Db.php.
Referenced by insert(), and update().
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/helper/Db.php