I-Tul Framework: Validate Class Reference
Validate Class Reference
Public Member Functions
run ($data, $rules)
Run validation.
print_checkbox ($field_name, $field_label, $field_value, $attribute_array=array(), $single_value=FALSE)
Return a checkbox field.
print_radio ($field_name, $field_label, $field_value, $attribute_array=array())
Return a radio field.
print_hidden ($field_name, $attribute_array=array())
Return a hidden field.
print_password ($field_name, $field_label, $attribute_array=array())
Return a password field.
print_textarea ($field_name, $field_label, $attribute_array=array())
Return a textarea field.
print_text ($field_name, $field_label, $attribute_array=array())
Return a text field.
print_select ($field_name, $field_label, $field_value, $attribute_array=array())
Return a dropdown field.
hide_errors ($hide_once=FALSE)
Do not show field errors.
show_errors ()
Show field errors.
hide_titles ($hide_once=FALSE)
Do not show field titles.
show_titles ()
Show field titles.
set_error ($error_array)
Set the error array.
set_data ($data_array)
Set the error array.
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Static Public Member Functions
static states ($show_blank=TRUE)
Array of state names (abbreviation => full name)
static months ($show_blank=TRUE, $format= 'M')
Array of months.
static number_range ($start, $end, $show_blank=TRUE)
Number range array.
static hours ()
Hours array.
Data Fields
$data
$rules
$error
Protected Member Functions
_build_wrapper_top ($field_name, $field_label, &$attribute_array)
Return header wrapper.
_build_wrapper_bottom ($attribute_array)
Return footer wrapper.
_set_field_type ($field_type)
Set the field type.
_get_field_type ($default_type)
Get the field type, return default if no type is set.
_get_field_value ($field_name)
Get a field value, initialize if not set.
_get_field_value_strip_array ($field_name)
Get a field value, initialize if not set If value is an array return first non empty value.
_build_field ($field_type, $field_name, $attribute_array)
Generate fields.
_process_attribute ($attribute_array)
Normalize attribute array.
_build_attribute ($attribute_array)
Build attribute string.
_rule_reqd ($field_name, $value, $error)
_rule_max ($field_name, $value, $error, $param=NULL)
_rule_min ($field_name, $value, $error, $param=NULL)
_rule_exact ($field_name, $value, $error, $param=NULL)
_rule_match ($field_name, $value, $error, $param=NULL)
_rule_alpha ($field_name, $value, $error)
_rule_numeric ($field_name, $value, $error)
_rule_positive ($field_name, $value, $error)
_rule_money ($field_name, $value, $error)
_rule_numeric_thousands ($field_name, $value, $error)
_rule_alphanumeric ($field_name, $value, $error)
_rule_no_space ($field_name, $value, $error)
_rule_email ($field_name, $value, $error)
_rule_date ($field_name, $value, $error)
_rule_time ($field_name, $value, $error)
_rule_unique ($field_name, $value, $error, $param=NULL)
_rule_exists ($field_name, $value, $error, $param=NULL)
_rule_cond ($field_name, $value, $error, $param=NULL)
Protected Attributes
$_field_type = NULL
$_hide_titles = FALSE
$_hide_titles_once = NULL
$_hide_errors = FALSE
$_hide_errors_once = NULL
Detailed Description
Definition at line 3 of file Validate.php.
Member Function Documentation
_build_attribute ($attribute_array) protected
Parameters
$attribute_array
Returns
string
Definition at line 589 of file Validate.php.
_build_field ($field_type, $field_name, $attribute_array) protected
Parameters
string $field_type
string $field_name
array $attribute_array
Returns
string
Definition at line 525 of file Validate.php.
Referenced by print_checkbox(), print_radio(), print_select(), and print_text().
_build_wrapper_bottom ($attribute_array) protected
Parameters
string $field_name
string $field_label
string $field_type
Returns
string
Definition at line 158 of file Validate.php.
Referenced by print_checkbox(), print_radio(), print_select(), and print_text().
_build_wrapper_top ($field_name, $field_label, & $attribute_array) protected
Parameters
string $field_name
string $field_label
string $field_type
string $hilight
Returns
string
Definition at line 97 of file Validate.php.
References show_errors(), and show_titles().
Referenced by print_checkbox(), print_radio(), print_select(), and print_text().
_get_field_type ($default_type) protected
Parameters
string $default_type
Returns
string
Definition at line 452 of file Validate.php.
References $_field_type.
Referenced by print_text().
_get_field_value ($field_name) protected
Parameters
string $field_name
Returns
string|array
Definition at line 473 of file Validate.php.
Referenced by _get_field_value_strip_array(), print_radio(), and print_select().
_get_field_value_strip_array ($field_name) protected
Parameters
string $field_name
Returns
string|array
Definition at line 496 of file Validate.php.
References _get_field_value().
_process_attribute ($attribute_array) protected
Parameters
array $attribute_array
Returns
array
Definition at line 553 of file Validate.php.
Referenced by print_checkbox(), print_hidden(), print_radio(), print_select(), and print_text().
_rule_alpha ($field_name, $value, $error) protected
Definition at line 917 of file Validate.php.
References $error.
_rule_alphanumeric ($field_name, $value, $error) protected
Definition at line 972 of file Validate.php.
References $error.
_rule_cond ($field_name, $value, $error, $param = NULL) protected
Definition at line 1080 of file Validate.php.
References $error.
_rule_date ($field_name, $value, $error) protected
Definition at line 1005 of file Validate.php.
References $error.
_rule_email ($field_name, $value, $error) protected
Definition at line 994 of file Validate.php.
References $error.
_rule_exact ($field_name, $value, $error, $param = NULL) protected
Definition at line 884 of file Validate.php.
References $error.
_rule_exists ($field_name, $value, $error, $param = NULL) protected
Definition at line 1059 of file Validate.php.
References $error, and Framework\load_helper().
_rule_match ($field_name, $value, $error, $param = NULL) protected
Definition at line 899 of file Validate.php.
References $error.
_rule_max ($field_name, $value, $error, $param = NULL) protected
Definition at line 854 of file Validate.php.
References $error.
_rule_min ($field_name, $value, $error, $param = NULL) protected
Definition at line 869 of file Validate.php.
References $error.
_rule_money ($field_name, $value, $error) protected
Definition at line 950 of file Validate.php.
References $error.
_rule_no_space ($field_name, $value, $error) protected
Definition at line 983 of file Validate.php.
References $error.
_rule_numeric ($field_name, $value, $error) protected
Definition at line 928 of file Validate.php.
References $error.
_rule_numeric_thousands ($field_name, $value, $error) protected
Definition at line 961 of file Validate.php.
References $error.
_rule_positive ($field_name, $value, $error) protected
Definition at line 939 of file Validate.php.
References $error.
_rule_reqd ($field_name, $value, $error) protected
Definition at line 843 of file Validate.php.
References $error.
_rule_time ($field_name, $value, $error) protected
Definition at line 1016 of file Validate.php.
References $error.
_rule_unique ($field_name, $value, $error, $param = NULL) protected
Definition at line 1028 of file Validate.php.
References $error, and Framework\load_helper().
_set_field_type ($field_type) protected
Parameters
string $field_type
Returns
Validate
Definition at line 439 of file Validate.php.
Referenced by print_hidden(), print_password(), and print_textarea().
hide_errors ($hide_once = FALSE)
Parameters
bool $hide_once
Returns
Validate
Definition at line 629 of file Validate.php.
hide_titles ($hide_once = FALSE)
Parameters
bool $hide_once
Returns
Validate
Definition at line 667 of file Validate.php.
static hours () static
Returns
array
Definition at line 812 of file Validate.php.
static months ($show_blank = TRUE, $format = 'M') static
Parameters
bool $show_blank
string $format
Returns
array
Definition at line 760 of file Validate.php.
static number_range ($start, $end, $show_blank = TRUE) static
Parameters
int $start
int $end
bool $show_blank
Returns
array
Definition at line 782 of file Validate.php.
print_checkbox ($field_name, $field_label, $field_value, $attribute_array = array(), $single_value = FALSE)
Parameters
string $field_name
string $field_label
array $field_value
array $attribute_array
bool $single_value
Returns
string
Definition at line 187 of file Validate.php.
References _build_field(), _build_wrapper_bottom(), _build_wrapper_top(), and _process_attribute().
print_hidden ($field_name, $attribute_array = array())
Parameters
string $field_name
array $attribute_array
Returns
string
Definition at line 318 of file Validate.php.
References _process_attribute(), and _set_field_type().
print_password ($field_name, $field_label, $attribute_array = array())
Parameters
string $field_name
string $field_label
array $attribute_array
Returns
string
Definition at line 337 of file Validate.php.
References _set_field_type().
print_radio ($field_name, $field_label, $field_value, $attribute_array = array())
Parameters
string $field_name
string $field_label
string $field_value
array $attribute_array
bool $single_value
Returns
string
Definition at line 257 of file Validate.php.
References _build_field(), _build_wrapper_bottom(), _build_wrapper_top(), _get_field_value(), and _process_attribute().
print_select ($field_name, $field_label, $field_value, $attribute_array = array())
Parameters
string $field_name
string $field_label
string $values
string $extra
Returns
string
Definition at line 395 of file Validate.php.
References _build_field(), _build_wrapper_bottom(), _build_wrapper_top(), _get_field_value(), and _process_attribute().
print_text ($field_name, $field_label, $attribute_array = array())
Parameters
string $field_name
string $field_label
array $attribute_array
Returns
string
Definition at line 367 of file Validate.php.
References _build_field(), _build_wrapper_bottom(), _build_wrapper_top(), _get_field_type(), and _process_attribute().
print_textarea ($field_name, $field_label, $attribute_array = array())
Parameters
string $field_name
string $field_label
array $attribute_array
Returns
string
Definition at line 352 of file Validate.php.
References _set_field_type().
run ($data, $rules)
Parameters
array $data
array $rules
Returns
bool
Definition at line 28 of file Validate.php.
References $data, and $rules.
set_data ($data_array)
Parameters
array $error_array
Returns
Validate
Definition at line 722 of file Validate.php.
set_error ($error_array)
Parameters
array $error_array
Returns
Validate
Definition at line 705 of file Validate.php.
show_errors ()
Returns
Validate
Definition at line 650 of file Validate.php.
Referenced by _build_wrapper_top().
show_titles ()
Returns
Validate
Definition at line 688 of file Validate.php.
Referenced by _build_wrapper_top().
static states ($show_blank = TRUE) static
Parameters
bool $show_blank
Returns
string
Definition at line 739 of file Validate.php.
References Framework\config().
Field Documentation
$_field_type = NULL protected
Definition at line 10 of file Validate.php.
Referenced by _get_field_type().
$_hide_errors = FALSE protected
Definition at line 17 of file Validate.php.
$_hide_errors_once = NULL protected
Definition at line 18 of file Validate.php.
$_hide_titles = FALSE protected
Definition at line 13 of file Validate.php.
$_hide_titles_once = NULL protected
Definition at line 14 of file Validate.php.
$data
Definition at line 5 of file Validate.php.
Referenced by run().
$error
Definition at line 7 of file Validate.php.
Referenced by _rule_alpha(), _rule_alphanumeric(), _rule_cond(), _rule_date(), _rule_email(), _rule_exact(), _rule_exists(), _rule_match(), _rule_max(), _rule_min(), _rule_money(), _rule_no_space(), _rule_numeric(), _rule_numeric_thousands(), _rule_positive(), _rule_reqd(), _rule_time(), and _rule_unique().
$rules
Definition at line 6 of file Validate.php.
Referenced by run().
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/helper/Validate.php