I-Tul Framework: Framework Class Reference
Framework Class Reference
Framework application class.
Public Member Functions
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Detailed Description
Base application class for the PHP Project CMS system
Definition at line 17 of file Framework.php.
Constructor & Destructor Documentation
__construct ()
Includes the system classes needed by framework
Definition at line 22 of file Framework.php.
Member Function Documentation
config ()
Gives easy access to $this->load_helper('Framework_Config')->load()
Returns
object Framework_Config - instance of all configuration setting in framework/config
Definition at line 402 of file Framework.php.
References load_helper().
Referenced by Framework_Route\__construct(), Controller_Base\add_error(), Controller_Base\css_url(), Encryption\decrypt_string(), Controller_Base\disable_header(), Encryption\encrypt_string(), Db_Override\get_row(), Db_Override\get_rows(), Controller_Base\image_url(), Controller_Base\javascript_url(), render(), render_foot(), render_head(), route(), and Validate\states().
is_id ($int_id)
Handles string and int input. Empty strings return FALSE.
Parameters
integer $int_id - value to check if it is an integer
Returns
boolean - true if value is an integer false otherwise
Definition at line 415 of file Framework.php.
Referenced by Framework_Route\__construct(), Model_Base\get(), Model_Base\limit(), and ORM_Base\orm_load().
load_controller ($module_name)
Definition at line 246 of file Framework.php.
Referenced by render(), and route().
load_helper ($module_name)
Definition at line 170 of file Framework.php.
References Framework_Config\Instance(), Db\Instance(), and Db_Override\Instance().
Referenced by ORM_Base\__call(), Scaffold\__construct(), Validate\_rule_exists(), Validate\_rule_unique(), config(), _Controller\delete(), Model_Base\exists(), Model_Base\get(), _Controller\index(), Model_Base\like(), _Controller\manage(), Model_Base\order(), ORM_Base\orm_delete(), ORM_Base\orm_load(), ORM_Base\orm_save(), Scaffold\paging_links(), render(), route(), User\send_reset_email(), and Model_Base\where().
load_model ($module_name, $force_new = FALSE)
Definition at line 127 of file Framework.php.
Referenced by ORM_Base\__call(), Error\__construct(), User\_user_password_to(), Auth\check_login(), _Controller\delete(), _Controller\manage(), render(), User_Controller\reset_password(), and User_Controller\update_password().
render ($page)
Rendering is the process of pushing the document buffers into the template placeholders, retrieving data from the document and pushing it into the buffer.
Parameters
string $page - template page to display (header, page, footer)
Definition at line 273 of file Framework.php.
References $frm, config(), exit, Auth\is_logged_in(), load_controller(), load_helper(), load_model(), render_foot(), and render_head().
render_foot ()
Each controller can supply/use it's own unique footer by simply placing a foot.php file in the framework/template/ControllerName/ subdirectory
Called by $this->render($page);
Definition at line 356 of file Framework.php.
References config().
Referenced by render().
render_head ()
Each controller can supply/use it's own unique header by simply placing a head.php file in the framework/template/ControllerName/ subdirectory
Called by $this->render($page);
Definition at line 334 of file Framework.php.
References config().
Referenced by render().
render_partial ($partial_name)
Each controller can supply/use it's own unique partial page elements by simply placing a $partial_name.php file in the framework/template/ControllerName/Partial subdirectory
Parameters
string $partial_name - name for the partial page element to load
Definition at line 377 of file Framework.php.
route ()
Routing is the process of examining the request environment to determine which module and page should receive the request.
Definition at line 44 of file Framework.php.
References $frm, config(), exit, load_controller(), load_helper(), and pr().
Referenced by Framework_Route\__construct().
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/Framework.php