I-Tul Framework: ORM_Base Class Reference
ORM_Base Class Reference
Base Object Relation Model class.
Public Member Functions
__construct ()
Construct function.
model_name ()
Get the current model name.
orm_load ($id=NULL)
Load an object.
__call ($name, $arguments)
Magic method override.
has_many ($table, $map_table=NULL)
Set one to many relationship.
has_one ($table, $map_table=NULL)
Set one to one relationship.
exists ($key_id)
Check if a primary key exists.
orm_hook ($event_name, $callback_method=NULL, $arguments=NULL)
Add an ORM event hook listener.
orm_set ($data_array)
Set orm data for an object.
orm_set_load ($data_array)
Set orm data for an object and mark as loaded.
is_loaded ()
Return if model is loaded.
orm_save ($additional_validation_array=array())
Save an object in the database.
orm_delete ()
Delete an object.
orm_transform ($column, $to_database, $from_database)
Transparent ORM column transformation.
expose_data ()
Debug data function.
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Protected Member Functions
_validate ()
Default validation function.
Protected Attributes
$_loaded = FALSE
boolean check to ensure object currently loaded via ORM_load call
$_data
array of data for object/model
$_to_many = array()
array defining one to many relationships
$_to_many_map = array()
array defining one to many relationships with mapping tables
$_to_one = array()
array defining one to one relationships
$_to_one_map = array()
array defining one to one relationships with mapping tables
$_transform = array()
array of transformation mappings for to/from tables
$_hook = array()
array of event hooks
Detailed Description
Abstract base class for CMS ORM classes
Definition at line 16 of file ORM_Base.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 70 of file ORM_Base.php.
Member Function Documentation
__call ($name, $arguments)
Parameters
string $name - method to call
array $arguments - parameters for method
Returns
mixed - instance of a ORM_Base derived class | array of ORM_Wrapper | unknown
Exceptions
Exception - if unable to identify/locate the method $name
Definition at line 146 of file ORM_Base.php.
References Framework\load_helper(), Framework\load_model(), and model_name().
_validate () protected
Should be defined/overridden in derived classes.
Returns
array - rules for validation functionality
Definition at line 597 of file ORM_Base.php.
Referenced by orm_save().
exists ($key_id)
Parameters
int $key_id - primary key to check existance of
Returns
bool - true if the key is found, false otherwise
Exceptions
Exception - if key is not numeric
Definition at line 344 of file ORM_Base.php.
expose_data ()
Returns
array
Definition at line 608 of file ORM_Base.php.
References $_data.
Referenced by _Controller\manage().
has_many ($table, $map_table = NULL)
Parameters
string $table
string $map_table
Returns
ORM_Base
Definition at line 285 of file ORM_Base.php.
has_one ($table, $map_table = NULL)
Parameters
string $table - name of the table/model
string $map_table - table with id to id relationship mapping
Returns
object - ORM_Base
Exceptions
Exception - if table doesn't exist
Definition at line 315 of file ORM_Base.php.
is_loaded ()
Returns
bool
Definition at line 450 of file ORM_Base.php.
References $_loaded.
model_name ()
Returns
string - lowercase model/class name
Definition at line 82 of file ORM_Base.php.
Referenced by __call(), Auth\__construct(), Model_Base\like(), Model_Base\order(), orm_load(), orm_save(), and Model_Base\where().
orm_delete ()
Returns
bool - true if object deleted from database
Exceptions
Exception - object not currently loaded via orm_load call
Definition at line 521 of file ORM_Base.php.
References Framework\load_helper().
orm_hook ($event_name, $callback_method = NULL, $arguments = NULL)
Parameters
string $event_name
string $callback_method
Returns
object - ORM_Base derived object
Definition at line 369 of file ORM_Base.php.
Referenced by orm_save().
orm_load ($id = NULL)
Parameters
int | string $id - primary key identifier for the object to load
Returns
mixed - instance or array of ORM_Wrapper
Exceptions
Exception - when id doesn't exist or the table doesn't exist
Definition at line 103 of file ORM_Base.php.
References Framework\is_id(), Framework\load_helper(), and model_name().
Referenced by Auth\__construct(), User\_user_password_to(), NAME\check_permission_load(), and orm_save().
orm_save ($additional_validation_array = array())
Returns
object - ORM loaded model
Exceptions
Exception - object fails validation routine for save
Definition at line 463 of file ORM_Base.php.
References _validate(), Framework\load_helper(), model_name(), orm_hook(), and orm_load().
orm_set ($data_array)
Parameters
array $data_array
Returns
object - ORM_Base derived object
Exceptions
Exception - if data is not an array
Definition at line 403 of file ORM_Base.php.
Referenced by User\send_reset_email().
orm_set_load ($data_array)
Parameters
array $data_array
Returns
object - ORM_Base derived object
Exceptions
Exception - if data is not an array
Definition at line 427 of file ORM_Base.php.
orm_transform ($column, $to_database, $from_database)
Pass a value through a model function on set/get
Parameters
string $column - name of column to transform
string $to_database - name of database to transform column to
string $from_database - name of database to transform column from
Returns
object - ORM_Base derived object
Definition at line 542 of file ORM_Base.php.
Referenced by User\__construct().
Field Documentation
$_data protected
Definition at line 28 of file ORM_Base.php.
Referenced by expose_data().
$_hook = array() protected
Definition at line 64 of file ORM_Base.php.
$_loaded = FALSE protected
Definition at line 22 of file ORM_Base.php.
Referenced by is_loaded().
$_to_many = array() protected
Definition at line 34 of file ORM_Base.php.
$_to_many_map = array() protected
Definition at line 40 of file ORM_Base.php.
$_to_one = array() protected
Definition at line 46 of file ORM_Base.php.
$_to_one_map = array() protected
Definition at line 52 of file ORM_Base.php.
$_transform = array() protected
Definition at line 58 of file ORM_Base.php.
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/ORM_Base.php