I-Tul Framework: Framework_Route Class Reference
Framework_Route Class Reference
Public Member Functions
__construct ()
controller ()
Expose the controller.
method ()
Expose the method.
vars ()
Expose the request vars.
raw ()
Expose the request raw array.
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Detailed Description
Definition at line 3 of file Framework_Route.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 10 of file Framework_Route.php.
References Framework\config(), Framework\is_id(), and Framework\route().
Member Function Documentation
controller ()
Definition at line 74 of file Framework_Route.php.
method ()
Definition at line 84 of file Framework_Route.php.
raw ()
Returns
array
Definition at line 106 of file Framework_Route.php.
vars ()
Todo:
implement
Definition at line 95 of file Framework_Route.php.
The documentation for this class was generated from the following file:
system/helper/Framework_Route.php