I-Tul Framework: Auth Class Reference
Auth Class Reference
Public Member Functions
__construct ()
is_logged_in ()
Check if a user is logged in.
logout ()
Clear login information from session.
Public Member Functions inherited from User
__construct ()
send_reset_email ()
Send a password update email.
Public Member Functions inherited from Model_Base
__construct ()
Construct function.
limit ($rows, $offset=FALSE)
Limit the number of items returned in the resultset.
order ($column, $value)
Set the result order.
where ($column, $value)
AND element to the where clause.
custom_where ($where)
AND element to the where clause.
like ($column, $value)
AND element to the where clause using LIKE.
get ($key_id=FALSE)
Get result set using where, order and limit clauses.
exists ($key_id)
Check if a primary key exists.
dropdown ($field_display_name, $blank_first=TRUE)
Create an array of column values ([ID] => [COLUMN VALUE]).
Public Member Functions inherited from ORM_Base
__construct ()
Construct function.
model_name ()
Get the current model name.
orm_load ($id=NULL)
Load an object.
__call ($name, $arguments)
Magic method override.
has_many ($table, $map_table=NULL)
Set one to many relationship.
has_one ($table, $map_table=NULL)
Set one to one relationship.
exists ($key_id)
Check if a primary key exists.
orm_hook ($event_name, $callback_method=NULL, $arguments=NULL)
Add an ORM event hook listener.
orm_set ($data_array)
Set orm data for an object.
orm_set_load ($data_array)
Set orm data for an object and mark as loaded.
is_loaded ()
Return if model is loaded.
orm_save ($additional_validation_array=array())
Save an object in the database.
orm_delete ()
Delete an object.
orm_transform ($column, $to_database, $from_database)
Transparent ORM column transformation.
expose_data ()
Debug data function.
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Static Public Member Functions
static check_login ($user_email, $user_password)
Check login credentials.
Additional Inherited Members
Protected Member Functions inherited from User
_validate ()
Model validation.
_user_password_to ($value)
Hash password to database.
_user_password_from ($value)
Return password from database.
Protected Attributes inherited from Model_Base
$_where
array of WHERE clause elements for resultset
$_order
array of ORDER BY clause elements to sort resultset
$_limit
string of LIMIT clause for resultset
Detailed Description
Definition at line 3 of file Auth.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 5 of file Auth.php.
References ORM_Base\model_name(), and ORM_Base\orm_load().
Member Function Documentation
static check_login ($user_email, $user_password) static
Parameters
string $user_email
string $user_password
Returns
bool|User
Definition at line 52 of file Auth.php.
References Framework\load_model().
is_logged_in ()
Returns
bool
Definition at line 27 of file Auth.php.
Referenced by Framework\render().
logout ()
Returns
bool
Definition at line 38 of file Auth.php.
Referenced by User_Controller\logout().
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/framework/model/Auth.php