I-Tul Framework: Model_Base Class Reference
Model_Base Class Reference
Base Model class.
Public Member Functions
__construct ()
Construct function.
limit ($rows, $offset=FALSE)
Limit the number of items returned in the resultset.
order ($column, $value)
Set the result order.
where ($column, $value)
AND element to the where clause.
custom_where ($where)
AND element to the where clause.
like ($column, $value)
AND element to the where clause using LIKE.
get ($key_id=FALSE)
Get result set using where, order and limit clauses.
exists ($key_id)
Check if a primary key exists.
dropdown ($field_display_name, $blank_first=TRUE)
Create an array of column values ([ID] => [COLUMN VALUE]).
Public Member Functions inherited from ORM_Base
__construct ()
Construct function.
model_name ()
Get the current model name.
orm_load ($id=NULL)
Load an object.
__call ($name, $arguments)
Magic method override.
has_many ($table, $map_table=NULL)
Set one to many relationship.
has_one ($table, $map_table=NULL)
Set one to one relationship.
exists ($key_id)
Check if a primary key exists.
orm_hook ($event_name, $callback_method=NULL, $arguments=NULL)
Add an ORM event hook listener.
orm_set ($data_array)
Set orm data for an object.
orm_set_load ($data_array)
Set orm data for an object and mark as loaded.
is_loaded ()
Return if model is loaded.
orm_save ($additional_validation_array=array())
Save an object in the database.
orm_delete ()
Delete an object.
orm_transform ($column, $to_database, $from_database)
Transparent ORM column transformation.
expose_data ()
Debug data function.
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Protected Attributes
$_where
array of WHERE clause elements for resultset
$_order
array of ORDER BY clause elements to sort resultset
$_limit
string of LIMIT clause for resultset
Protected Attributes inherited from ORM_Base
$_loaded = FALSE
boolean check to ensure object currently loaded via ORM_load call
$_data
array of data for object/model
$_to_many = array()
array defining one to many relationships
$_to_many_map = array()
array defining one to many relationships with mapping tables
$_to_one = array()
array defining one to one relationships
$_to_one_map = array()
array defining one to one relationships with mapping tables
$_transform = array()
array of transformation mappings for to/from tables
$_hook = array()
array of event hooks
Additional Inherited Members
Protected Member Functions inherited from ORM_Base
_validate ()
Default validation function.
Detailed Description
Abstract base class for CMS model classes
Definition at line 16 of file Model_Base.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 38 of file Model_Base.php.
Member Function Documentation
custom_where ($where)
Parameters
string $where
Returns
object - self/this
Definition at line 121 of file Model_Base.php.
dropdown ($field_display_name, $blank_first = TRUE)
Uses the primary key for the table as ID
Parameters
string $field_display_name - COLUMN VALUE to display in dropdown, should match table column name
bool $blank_first - display a blank line as the first value, default is true
Returns
array - result set usable in Validate->print_select statements
Exceptions
Exception - blank param is not a boolean or display field is not a column in the table
Definition at line 241 of file Model_Base.php.
exists ($key_id)
Parameters
int $key_id - specific primary key id to check
Returns
bool - true if primary key is found, false otherwise
Exceptions
Exception - if key is not numeric
Definition at line 215 of file Model_Base.php.
References Framework\load_helper().
Referenced by NAME\check_permission_load().
get ($key_id = FALSE)
Resets where, order and limit clauses.
Parameters
int $key_id - specific primary key id to retrieve, default retrieves all
Returns
object - DB_Wrapper of result set returned or empty
See Also
DB_Wrapper
Definition at line 157 of file Model_Base.php.
References Db\get_rows(), Framework\is_id(), Framework\load_helper(), and Db_Wrapper\set().
like ($column, $value)
Parameters
string $column - column name to add to WHERE clause array
string $value - pattern column must be like, add widlcards % _ to value to expand match
Returns
object - self/this
Exceptions
Exception - if column does not exist in the database table for the model
Definition at line 137 of file Model_Base.php.
References Framework\load_helper(), and ORM_Base\model_name().
limit ($rows, $offset = FALSE)
Parameters
int $rows - number of rows to return
int $offset - page offset, defaults to 0 (first page)
Returns
object - self/this
Exceptions
Exception - if rows not greater than 0 or offset isn't an integer
Definition at line 53 of file Model_Base.php.
References Framework\is_id().
order ($column, $value)
Parameters
string $column - column name to sort results by
string $order - ordinality of sort, DESC for descending ASC for ascending
Returns
object - self/this
Exceptions
Exception - if column does not exist or ordinality is not DESC or SC
Definition at line 78 of file Model_Base.php.
References Framework\load_helper(), and ORM_Base\model_name().
where ($column, $value)
Parameters
string $column - column name to add to WHERE clause array
string $value - value column must be equal to
Returns
object - self/this
Exceptions
Exception - if column does not exist in the database table for the model
Definition at line 103 of file Model_Base.php.
References Framework\load_helper(), and ORM_Base\model_name().
Field Documentation
$_limit protected
Definition at line 32 of file Model_Base.php.
$_order protected
Definition at line 27 of file Model_Base.php.
$_where protected
Definition at line 22 of file Model_Base.php.
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/Model_Base.php