I-Tul Framework: Controller_Base Class Reference
Controller_Base Class Reference
Controller Base class.
Public Member Functions
__construct ()
Constructor for Controller_Base.
add_error ($error)
Add error to Session error variable.
show_error ()
Display the Session error variable.
add_flash ($message)
Add an information message to Session flash variable.
show_flash ()
Display the Session flash variable.
image_url ($path)
Get path to an image file.
javascript_url ($path)
Get path to a javascript file.
css_url ($path)
Get path to a CSS file.
reload_page ()
Reload the current page.
page_link ($controller= '', $method= '', $id= '')
Return the path to a page.
redirect ($controller= '', $method= '', $id= '')
Redirect to a page.
active ($compare= '')
Sets the active class for a page.
disable_header ($mixed=NULL)
Disable single or multiple page headers.
require_login ($pages_requiring_login=NULL, $pages_to_exclude=NULL)
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Detailed Description
Abstract Base application class for the PHP Project CMS system
Definition at line 16 of file Controller_Base.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 21 of file Controller_Base.php.
Member Function Documentation
active ($compare = '')
Parameters
string $compare - page to check if its the current one
Definition at line 224 of file Controller_Base.php.
References $c.
add_error ($error)
For display later with show_error(). Only sets session variable if configuration log_error is true
Parameters
mixed $error - a string or array or errors to display
Returns
object Controller_Base
Definition at line 35 of file Controller_Base.php.
References Framework\config().
add_flash ($message)
For display later with show_flash().
Parameters
string $message - Message to display to the user
Returns
object Controller_Base
Definition at line 80 of file Controller_Base.php.
Referenced by User_Controller\reset_password(), and User_Controller\update_password().
css_url ($path)
Creates a string usable in href's to the CSS file.
Parameters
string $path - the name of the file, which can include subdirectories of the framework/template/css folder
Returns
string - Full web path to the file
Definition at line 160 of file Controller_Base.php.
References $path, and Framework\config().
disable_header ($mixed = NULL)
Parameters
string|array
Returns
Controller_Base
Definition at line 248 of file Controller_Base.php.
References Framework\config().
image_url ($path)
Creates a string usable in href's to the image.
Parameters
string $path - the name of the file, which can include subdirectories of the framework/template/images folder
Returns
string - Full web path to the file
Definition at line 118 of file Controller_Base.php.
References $path, and Framework\config().
javascript_url ($path)
Creates a string usable in href's to the JavaScript file.
Parameters
string $path - the name of the file, which can include subdirectories of the framework/template/js folder
Returns
string - Full web path to the file
Definition at line 139 of file Controller_Base.php.
References $path, and Framework\config().
page_link ($controller = '', $method = '', $id = '')
Creates a string usable in href's to the page.
Parameters
string $controller - controller for the page
string $method - method name for the page
string $id - optional id or other parameters for method
Returns
string - Full web path to the page with supplied aguments if anny
Definition at line 194 of file Controller_Base.php.
redirect ($controller = '', $method = '', $id = '')
Parameters
string $controller - controller for the page
string $method - method name for the page
string $id - optional id or other parameters for method
Definition at line 211 of file Controller_Base.php.
References exit.
Referenced by User_Controller\logout().
reload_page ()
Definition at line 177 of file Controller_Base.php.
References exit.
require_login ($pages_requiring_login = NULL, $pages_to_exclude = NULL)
Definition at line 296 of file Controller_Base.php.
Referenced by Dashboard_Controller\__construct().
show_error ()
Shows previously set errors from add_error() and removes/empties Session error variable.
Definition at line 58 of file Controller_Base.php.
show_flash ()
Shows previously set informational messages from add_flash() and removes/empties Session flash variable.
Definition at line 95 of file Controller_Base.php.
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/Controller_Base.php