I-Tul Framework: Scaffold Class Reference
Scaffold Class Reference
Public Member Functions
__construct ()
set_column_display ($column_array)
set_join_table ($table_1, $column_1, $table_2, $column_2)
set_items_per_page ($rows)
set_page_number ($page)
set_sort_order ($order)
set_sort_column ($column_name)
set_table_name ($table_name)
set_search_term ($search_term)
search ()
sort_column_link ($column_name, $debug=FALSE)
column_link_class ($column)
column_display ()
paging_links ($current_page_url)
config ()
results ()
Public Member Functions inherited from Framework
__construct ()
Constructor for the framework.
route ()
Route the application.
load_model ($module_name, $force_new=FALSE)
load_helper ($module_name)
load_controller ($module_name)
render ($page)
Render the application.
render_head ()
Render the header for the current page.
render_foot ()
Render the footer for the current page.
render_partial ($partial_name)
Render a partial element for the current page.
config ()
Loads the framework configuration.
is_id ($int_id)
Check if a value is an integer id.
Detailed Description
Definition at line 3 of file Scaffold.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 13 of file Scaffold.php.
References Framework\load_helper().
Member Function Documentation
column_display ()
Definition at line 354 of file Scaffold.php.
column_link_class ($column)
Definition at line 339 of file Scaffold.php.
config ()
Definition at line 396 of file Scaffold.php.
paging_links ($current_page_url)
Definition at line 360 of file Scaffold.php.
References Framework\load_helper(), and Paginate\show_page_links().
results ()
Definition at line 402 of file Scaffold.php.
Referenced by search().
search ()
Definition at line 154 of file Scaffold.php.
References Db\get_primary_key(), Db\get_row(), Db\get_rows(), and results().
set_column_display ($column_array)
Definition at line 34 of file Scaffold.php.
set_items_per_page ($rows)
Definition at line 78 of file Scaffold.php.
set_join_table ($table_1, $column_1, $table_2, $column_2)
Definition at line 52 of file Scaffold.php.
References Db\column_exists().
set_page_number ($page)
Definition at line 91 of file Scaffold.php.
set_search_term ($search_term)
Definition at line 144 of file Scaffold.php.
set_sort_column ($column_name)
Definition at line 117 of file Scaffold.php.
set_sort_order ($order)
Definition at line 104 of file Scaffold.php.
set_table_name ($table_name)
Definition at line 132 of file Scaffold.php.
References Db\get_table_info().
sort_column_link ($column_name, $debug = FALSE)
Definition at line 298 of file Scaffold.php.
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/helper/Scaffold.php