I-Tul Framework: Db_Wrapper Class Reference
Db_Wrapper Class Reference
Wrapper Database class.
Public Member Functions
set ($array)
Populate the data array.
result ()
Get first result from data array.
results ()
Get all results from data array.
count ()
Counts the number of items in data array.
Detailed Description
Wrapper class for raw database resultsets
Definition at line 16 of file Db_Wrapper.php.
Member Function Documentation
count ()
Returns
integer - number of items in array or 0 if empty
Definition at line 78 of file Db_Wrapper.php.
Referenced by results().
result ()
Returns
mixed - result from first element or boolean false if no data
Definition at line 44 of file Db_Wrapper.php.
results ()
Returns
mixed - array or results or boolean false if no data
Definition at line 61 of file Db_Wrapper.php.
References count().
set ($array)
Parameters
array $array - raw result set from query
Returns
object Db_Wrapper
Definition at line 30 of file Db_Wrapper.php.
Referenced by Model_Base\get().
The documentation for this class was generated from the following file:
C:/Projects/itul/devel/framework/system/Db_Wrapper.php