I-Tul Framework: cli.php File Reference
cli.php File Reference
Functions
console_text ($string, $formatting= '')
Variables
$using_cli = (@$_SERVER['argc'] >= 1)
if ($using_cli===FALSE)
$frm = new Framework
$plugins = array()
$path = __DIR__."/system/cli/"
$handle = opendir($path)
while(false!==($file=readdir($handle))) if (isset($plugins[ucfirst($_SERVER['argv'][1])]))
foreach($plugins as $param=>
$plugin) exit
if ($_SERVER['argv'][1]== 'build')
Function Documentation
console_text ($string, $formatting = '')
Definition at line 104 of file cli.php.
Referenced by CLI_Generate\start().
Variable Documentation
$frm = new Framework
Definition at line 15 of file cli.php.
Referenced by Framework\route().
$handle = opendir($path)
Definition at line 22 of file cli.php.
Referenced by Framework_Config\load().
$path = __DIR__."/system/cli/"
Definition at line 21 of file cli.php.
Referenced by Controller_Base\css_url(), Controller_Base\image_url(), and Controller_Base\javascript_url().
$plugins = array()
Definition at line 18 of file cli.php.
$using_cli = (@$_SERVER['argc'] >= 1)
Definition at line 7 of file cli.php.
foreach ($plugins as $param=> $plugin) exit
Definition at line 56 of file cli.php.
Referenced by Controller_Base\reload_page(), Framework\render(), User_Controller\reset_password(), Framework\route(), and User_Controller\update_password().
if($using_cli===FALSE)
Definition at line 8 of file cli.php.
while (false!==($file=readdir($handle))) if(isset($plugins[ucfirst($_SERVER['argv'][1])]))
Definition at line 36 of file cli.php.
if($_SERVER['argv'][1]== 'build')
Definition at line 66 of file cli.php.